Allow restart arg for init scripts

diff --git a/source/dist/util/rctemplates/sgeexecd_template b/source/dist/util/rctemplates/sgeexecd_template
--- a/source/dist/util/rctemplates/sgeexecd_template
+++ b/source/dist/util/rctemplates/sgeexecd_template
@@ -109,7 +109,7 @@ case $ARCH in
 esac
 
 #---------------------------------------------------------------------------
-# DetectSMFService - sets service to a mask maching the name
+# DetectSMFService - sets service to a mask matching the name
 # $1 ... name
 #
 DetectSMFService()
@@ -194,7 +194,7 @@ Shutdown()
 #---------------------------------------------------------------------------
 # GetPathToBinaries
 #    echo the name of the bin_dir on this system
-#    The check is fullfilled if we can access the qstat binary
+#    The check is fulfilled if we can access the qstat binary
 #    echo "none" if we can't determine the binary path
 GetPathToBinaries()
 {
@@ -239,8 +239,8 @@ GetAdminUser()
 
 #---------------------------------------------------------------------------
 # GetPathToUtilbin
-#    echo the path to the binaires in utilbin
-#    The check is fullfilled if we can access the "gethostname" binary
+#    echo the path to the binaries in utilbin
+#    The check is fulfilled if we can access the "gethostname" binary
 #    echo "none" if we can't determine the binary path
 #
 GetPathToUtilbin()
@@ -277,12 +277,13 @@ usage()
    echo "Grid Engine start/stop script. Valid parameters are:"
    echo ""
    echo "   (no parameters): start execution daemon if applicable"
-   echo "   \"start\"        dto."
+   echo "   \"start\"        ditto."
    echo "   \"stop\"         shutdown local Grid Engine processes and jobs"
    echo "   \"softstop\"     shutdown local Grid Engine processes (no jobs)"
+   echo "   \"restart\"      restart local Grid Engine processes (keeping jobs)"
    echo "   \"-nosmf\"       force no SMF"
    echo ""
-   echo "Only one of the parameters \"start\", \"stop\" or \"softstop\" is allowed."
+   echo "Only one of \"start\", \"stop\", \"restart\", or \"softstop\" is allowed."
    echo
    echo "Default argument is \"start\" for all components."
    echo "Default for \"stop\" is shutting down all components."
@@ -299,21 +300,24 @@ if [ "$#" -gt 2 -o "$1" = "-h" -o "$1" = "help" ]; then
    usage
 fi
 
-startup=true
+startup=false
 execd=true
 softstop=false
+stop=false
 noSMF=false
 
 for i in $*; do
    if [ "$i" = start ]; then
       startup=true
    elif [ "$i" = stop ]; then
-      startup=false
+      stop=true
    elif [ "$i" = softstop ]; then
-      startup=false
       softstop=true
    elif [ "$i" = -nosmf ]; then
       noSMF=true
+   elif [ "$i" = restart ]; then
+      startup=true
+      stop=true
    else
       usage
    fi
@@ -322,13 +326,13 @@ done
 bin_dir=`GetPathToBinaries`
 if [ "$bin_dir" = "none" ]; then
    echo "can't determine path to Grid Engine binaries"
-   exit 1
+   exit 5  # LSB compliant exit status - program is not installed
 fi
 
 utilbin_dir=`GetPathToUtilbin`
 if [ "$utilbin_dir" = "none" ]; then
    echo "can't determine path to Grid Engine utility binaries"
-   exit 1
+   exit 5  # LSB compliant exit status - program is not installed
 fi
 
 # HOST is the aliased name (SGE name)
