Fix #1412: check in init script that shepherd will load
Ignore-this: eb563962bd42df45868b0a29fcddf3c9
Exit 0 from sge_shepherd -help

darcs-hash:8e8558602045562300520947b454ef658b3dbafb

diff --git a/source/dist/util/rctemplates/sgeexecd_template b/source/dist/util/rctemplates/sgeexecd_template
--- a/source/dist/util/rctemplates/sgeexecd_template
+++ b/source/dist/util/rctemplates/sgeexecd_template
@@ -388,6 +388,12 @@ if [ $stop = true -o $softstop = true ]; then
 fi
 
 if [ "$startup" = true ]; then
+      # Ensure the shepherd will run, e.g. not missing hwloc dynamic lib
+      if ! $bin_dir/sge_shepherd -help >/dev/null 2>&1; then
+          echo "sge_shepherd won't run -- dynamic library missing?"
+          exit 5
+      fi
+
       #We want to use smf
       if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
          svcadm enable -st $service
