Allow restart arg for init scripts
Ignore-this: c05accdf53b998cd80e40f5c1dd0f913

darcs-hash:da91036a38999c03dab7f563a9e761cdc8e1948a

diff --git a/source/dist/util/rctemplates/sgemaster_template b/source/dist/util/rctemplates/sgemaster_template
--- a/source/dist/util/rctemplates/sgemaster_template
+++ b/source/dist/util/rctemplates/sgemaster_template
@@ -48,6 +48,7 @@
 #
 #       start       start qmaster or shadowd 
 #       stop        Terminates qmaster if we are on the master machine.
+#       restart     equivalent to stop followed by start
 #       -qmaster    only starts qmaster 
 #       -shadowd    start shadwod if found in the "shadow_masters" file
 #       -migrate    shuts down qmaster if it is running
@@ -259,7 +260,7 @@ CheckIfShadowMasterHost()
 #---------------------------------------------------------------------------
 # GetPathToBinaries
 #    echo the name of the bin_dir on this system
-#    The check is fullfilled if we can access the qstat binary
+#    The check is fulfilled if we can access the qstat binary
 #    echo "none" if we can't determine the binary path
 GetPathToBinaries()
 {
@@ -304,8 +305,8 @@ GetAdminUser()
 
 #---------------------------------------------------------------------------
 # GetPathToUtilbin
-#    echo the path to the binaires in utilbin
-#    The check is fullfilled if we can access the "gethostname" binary
+#    echo the path to the binaries in utilbin
+#    The check is fulfilled if we can access the "gethostname" binary
 #    echo "none" if we can't determine the binary path
 #
 GetPathToUtilbin()
@@ -393,7 +394,7 @@ CheckRunningQmaster()
 }
 
 #---------------------------------------------------------------------------
-# DetectSMFService - sets service to a mask maching the name
+# DetectSMFService - sets service to a mask matching the name
 # $1 ... name
 #
 DetectSMFService()
@@ -430,8 +431,9 @@ usage()
    echo "Grid Engine start/stop script. Valid parameters are:"
    echo ""
    echo "   (no parameters): start qmaster and shadow daemon if applicable"
-   echo "   \"start\"        dto."
-   echo "   \"stop\"         shutdown local Grid Engine processes and jobs"
+   echo "   \"start\"        ditto."
+   echo "   \"stop\"         shut down qmaster and shadow daemon if applicable"
+   echo "   \"restart\"      restart (stop and start) daemons"
    echo "   \"-qmaster\"     only start/stop qmaster (if applicable)"
    echo "   \"-shadowd\"     only start/stop shadowd (if applicable)"   
    echo "   \"-migrate\"     shutdown qmaster if it's running on another"
@@ -439,7 +441,7 @@ usage()
    echo "                    Migration only works if this host is an admin host"
    echo "   \"-nosmf\"       force no SMF"
    echo ""
-   echo "Only one of the parameters \"start\", \"stop\" or \"softstop\" is allowed."
+   echo "Only one of \"start\", \"stop\", \"restart\", or \"softstop\" is allowed."
    echo "Only one of the parameters beginning  with \"-\" is allowed. Does not " 
    echo "apply to -nosmf."
    echo
@@ -463,17 +465,18 @@ qmaster=true
 shadowd=true
 qstd=false
 migrate_qmaster=false
-softstop=false
 noSMF=false
+stop=false
 
 for i in $*; do
    if [ "$i" = start ]; then
       startup=true
    elif [ "$i" = stop ]; then
       startup=false
-   elif [ "$i" = softstop ]; then
-      startup=false
-      softstop=true
+      stop=true
+   elif [ "$i" = restart ]; then
+       stop=true
+       startup=true
    elif [ "$i" = -qmaster ]; then
       qmaster=true
       shadowd=false
@@ -494,19 +497,60 @@ done
 bin_dir=`GetPathToBinaries`
 if [ "$bin_dir" = "none" ]; then
    echo "can't determine path to Grid Engine binaries"
-   exit 1
+   exit 5	# LSB compliant exit status - program is not installed
 fi
 
 utilbin_dir=`GetPathToUtilbin`
 if [ "$utilbin_dir" = "none" ]; then
    echo "can't determine path to Grid Engine utility binaries"
-   exit 1
+   exit 5	# LSB compliant exit status - program is not installed
 fi
 
 HOST=`$utilbin_dir/gethostname -aname`
 UQHOST=`$utilbin_dir/gethostname -aname | cut -f1 -d.`
 qmaster_spool_dir=`QmasterSpoolDir`
 CheckIfShadowMasterHost $HOST
+
+if [  "$stop" = true ]; then
+   if [ $shadowd = true -a $shadow_host = true ]; then
+      echo "   shutting down Grid Engine shadowd"
+      DetectSMFService shadowd
+      if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
+         svcadm disable -st $service
+      else
+         # Send SIGTERM to shadowd
+         if [ -f $qmaster_spool_dir/shadowd_$UQHOST.pid ]; then
+            Shutdown sge_shadowd $qmaster_spool_dir/shadowd_$UQHOST.pid
+         elif [ -f $qmaster_spool_dir/shadowd_$HOST.pid ]; then
+            Shutdown sge_shadowd $qmaster_spool_dir/shadowd_$HOST.pid
+         fi	
+      fi
+   fi
+
+   if [ $qmaster = true ]; then
+      if [ `CheckIfQmasterHost $HOST` = true ]; then
+         echo "   shutting down Grid Engine qmaster"
+         DetectSMFService qmaster
+         if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
+            svcadm disable -st $service
+            exit $?
+         else
+            # Send SIGTERM to qmaster
+            Shutdown sge_qmaster $qmaster_spool_dir/qmaster.pid
+            ret=$?
+            if [ -f /var/lock/subsys/sgemaster ]; then
+               uid=`$utilbin_dir/uidgid -uid`
+               if [ "$uid" = "0" -a "$ret" = "0" ]; then            
+                  rm -f /var/lock/subsys/sgemaster >/dev/null 2>&1
+               else
+                  echo "Can't shut down qmaster!"
+                  exit 1
+               fi
+            fi
+         fi
+      fi
+   fi
+fi
 
 if [ "$startup" = true ]; then
    
@@ -533,7 +577,7 @@ if [ "$startup" = true ]; then
        echo "   shutting down qmaster on host \"$actual_qmaster_host\" ..."
        qconf_output=`$bin_dir/qconf -ks 2>&1 | grep "denied"`
        if [ "$qconf_output" != "" ]; then
-          echo "   denied: host \"$HOST\" is no admin host."
+          echo "   denied: host \"$HOST\" is not an admin host."
           exit 1
        fi
        $bin_dir/qconf -km > /dev/null 2>&1
@@ -725,45 +769,6 @@ if [ "$startup" = true ]; then
       
    if [ $exit_val -ne 0 ]; then
       exit $exit_val
-   fi
-else
-   if [ $shadowd = true -a $shadow_host = true ]; then
-      echo "   shutting down Grid Engine shadowd"
-      DetectSMFService shadowd
-      if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
-         svcadm disable -st $service
-      else
-         # Send SIGTERM to shadowd
-         if [ -f $qmaster_spool_dir/shadowd_$UQHOST.pid ]; then
-            Shutdown sge_shadowd $qmaster_spool_dir/shadowd_$UQHOST.pid
-         elif [ -f $qmaster_spool_dir/shadowd_$HOST.pid ]; then
-            Shutdown sge_shadowd $qmaster_spool_dir/shadowd_$HOST.pid
-         fi	
-      fi
-   fi
-
-   if [ $qmaster = true ]; then
-      if [ `CheckIfQmasterHost $HOST` = true ]; then
-         echo "   shutting down Grid Engine qmaster"
-         DetectSMFService qmaster
-         if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
-            svcadm disable -st $service
-            exit $?
-         else
-            # Send SIGTERM to qmaster
-            Shutdown sge_qmaster $qmaster_spool_dir/qmaster.pid
-            ret=$?
-            if [ -f /var/lock/subsys/sgemaster ]; then
-               uid=`$utilbin_dir/uidgid -uid`
-               if [ "$uid" = "0" -a "$ret" = "0" ]; then            
-                  rm -f /var/lock/subsys/sgemaster >/dev/null 2>&1
-               else
-                  echo "Can't shut down qmaster!"
-                  exit 1
-               fi
-            fi
-         fi
-      fi
    fi
 
 fi
