Unify GNU/Linux arch strings (from Univa)

diff --git a/source/dist/util/arch b/source/dist/util/arch
--- a/source/dist/util/arch
+++ b/source/dist/util/arch
@@ -46,10 +46,6 @@
 # with the user's path instead of our "safe" one.  Thus we need to
 # save the old value of PATH for later restoration.
 #
-# This arch script is used from users building the source code for themselfs. 
-# 
-# PLEASE UPDATE CHANGES IN THE SCRIPT WHICH HAVE TO APPEAR IN THE DISTRIBUTION
-# ALSO IN THE arch.dist SCRIPT! 
 
 SAFE_PATH=/bin:/usr/bin:/usr/sbin
 OLD_PATH=$PATH
@@ -241,54 +237,49 @@ Linux)
    # It's most robust to use the glibc API, but this should work on
    # the supported patforms anyhow.  See section 4.9 in
    # http://sourceware.org/git/?p=glibc.git;a=blob_plain;f=FAQ;hb=HEAD
-   case $osrelease in
-   2.4.*)
-      lxrelease=24
+   if [ "$unsupported" != "UNSUPPORTED-" ]; then
+      case $osrelease in
+      2.4.*|2.6.*)
+         # verify the GNU C lib version
+         # we expect libc version to be
+         # >= 2.3 - this is our supported lx-* platform
+         # == 2.2 - unsupported but known to build and work: ulx-* platform
+         # <= 2.2 - not accepted as build or execution platform
+         case $lxmachine in
+         amd64)
+            libc=/lib64/libc.so.6
+            ;;
+         ia64)
+            libc=/lib/libc.so.6.1
+            ;;
+         *)
+            libc=/lib/libc.so.6
+            ;;
+         esac
 
-      # verify the GNU C lib version
-      case $lxmachine in
-      amd64)
-         libc=/lib64/libc.so.6
-         ;;
-      ia64)
-         libc=/lib/libc.so.6.1
-         ;;
-      *)
-         libc=/lib/libc.so.6
-         ;;
-      esac
-
-      libc_string=`$libc | head -n 1`
-      # retrieving libc version failed
-      if [ $? -ne 0 ]; then
-         unsupported="UNSUPPORTED-"
-         lxrelease="24-GLIBC"
-      else
-         libc_version=`expr "$libc_string" : ".* version [0-9]*\\.\([0-9]*\)[^0-9]" 2>/dev/null`
-	 if expr "$libc_version" : "[0-9][0-9]*$" >/dev/null 2>&1; then
-            if [ $? -ne 0 -o $? -ne 0 -o $libc_version -lt 2 ]; then
-               unsupported="UNSUPPORTED-"
-               lxrelease=24-GLIBC-2.${libc_version}
-            else
-               if [ $libc_version -eq 2 ]; then
-                  unsupported="u"
+         libc_string=`$libc | head -n 1`
+         # retrieving libc version failed
+         if [ $? -ne 0 ]; then
+            unsupported="UNSUPPORTED-"
+         else
+            libc_version=`expr "$libc_string" : ".* version [0-9]*\\.\([0-9]*\)[^0-9]" 2>/dev/null`
+            if expr "$libc_version" : "[0-9][0-9]*$" >/dev/null 2>&1; then
+               if [ $? -ne 0 -o $? -ne 0 -o $libc_version -lt 2 ]; then
+                  unsupported="UNSUPPORTED-GLIBC-2.${libc_version}"
+               else
+                  if [ $libc_version -eq 2 ]; then
+                     unsupported="u"
+                  fi
                fi
             fi
-   	 else
-            unsupported="UNSUPPORTED-"
-            lxrelease=24-GLIBC-2.${libc_version}
-	 fi
+         fi
+         ;;
+      *)
+         unsupported="UNSUPPORTED-$osrelease"
+      esac
       fi
+      ARCH=${unsupported}lx-${lxmachine}
       ;;
-   2.6.*)
-      lxrelease=26
-      ;;
-   *)
-      unsupported="UNSUPPORTED-"
-      lxrelease=$osrelease
-   esac
-   ARCH=${unsupported}lx${lxrelease}-${lxmachine}
-   ;;
 OSF1)
    case $osrelease in
    V4*)
@@ -424,7 +415,7 @@ if [ "$1" = "-m" -o "$1" = "-mt" -o "$1" = "-lib" ]; then
       # if bit-specific variable already set, use this variable!
       SHARED_LIBRARY_PATH_BITS="LD_LIBRARY_PATH_`isainfo -b`"
       if eval [ x\$$SHARED_LIBRARY_PATH_BITS != x ]; then
-	      SHARED_LIBRARY_PATH=$SHARED_LIBRARY_PATH_BITS
+              SHARED_LIBRARY_PATH=$SHARED_LIBRARY_PATH_BITS
       fi
       ;;
    tru64)
