Various changes (fom Univa)
Ignore-this: 86bc89e7b3c377ddd44907f731e59c68
build env changes for uge extensions
suspend changes to qrsh client
added os-stub code for qrsh suspend feature
qrsh suspend changes for shepherd
double include of a header file

darcs-hash:43608a748bfadba16a410819ac42e3b9d4fd8e38

diff --git a/source/aimk b/source/aimk
--- a/source/aimk
+++ b/source/aimk
@@ -133,6 +133,9 @@ while ($i <= $#argv)
    set i = `expr $i + 1`
 end
 
+# Initialize extern variables from aimk.*
+set UGE_LIBS         = 0   # Path to Univa Extensions
+
 # Source variables for definition of site dependent paths of software here
 #
 if ( -f aimk.site ) then
@@ -222,6 +225,7 @@ usage:
    echo "-sunman           -> create man pages for Sun branded man pages (with -man)"
    echo "-system-libs      -> use dynamic system libraries (specifically libssl)"
    echo "-tight-ssh        -> compile SSH daemon with tight SGE integration"
+   echo "-uge-ext          -> build binaries with Univa Extensions"
    echo "-umap             -> compile with usermapping and hostgroup feature (currently broken)"
    echo "-with-jemalloc    -> build SGE with the jemalloc library (default on GNU/Linux)"
   exit
@@ -241,6 +245,7 @@ set MSDIR            = ""
 set MAKEFILE         = "${SDIR}/common/Makefile.global"
 set SOLARIS_ONLY_64  = 0
 set ONLY_PARAM_SPEC  = 0
+set LIBS_DIR         = "${SDIR}"
 
 # SGE_INPUT_CFLAGS will be taken from environment and added to CFLAGS
 if ( $?SGE_INPUT_CFLAGS ) then
@@ -317,7 +322,7 @@ set TPLIB            = ""  # 3rdparty libs
 set SLIBS            = ""
 set FLAGS_OUT        = "false"
 set DUMP             = 1
-
+set UGE_EXT          = 0   # Univa Extensions
 
 # Default settings for shared library creation
 set SHAREDLIBS       = 0
@@ -613,6 +618,9 @@ while ($#argv >= 1 && $?found)
       breaksw
    case "-no-dump":
       set DUMP = 0
+      breaksw
+   case "-uge-ext":
+      set UGE_EXT = 1
       breaksw
    case  "-no-java"
       set JAVA = 0
@@ -2014,6 +2022,21 @@ set ARCH_STRING  = SGE_ARCH_STRING='\"'${buildarch}'\"'
 set CFLAGS       = "-D$ARCH_STRING $CFLAGS"
 set DEPEND_FLAGS = "-D$ARCH_STRING $DEPEND_FLAGS"
 
+if ( $UGE_EXT == 1 ) then
+  if ( -d $UGE_LIBS ) then
+     set LFLAGS   = "$LFLAGS -L$UGE_EXT/$BUILDARCH/libs"
+     set LIBS_DIR = "$UGE_LIBS"
+  else
+     echo "error: couldn't find  UGE_LIBS"
+     echo "error: please"
+     echo "error: (a) update UGE_LIBS in aimk.site or aimk.private accordingly"
+     echo "error: (b) do not use aimk option -uge-ext"
+     exit 1
+  endif
+else
+  set LIBS_DIR = ${SDIR}
+endif
+
 if ( $JNI == 1 ) then
    set CORE_INCLUDE = "$CORE_INCLUDE -I${JAVA_HOME}/${JAVA_INCL}"
 
@@ -2626,6 +2649,7 @@ if ( "$CORE" == 1 && "$JAVA" != 2 ) then
          "CORELIB=$CORELIB" "LIBCORE=$LIBCORE" \
          "DEPEND_FLAGS=$DEPEND_FLAGS $CORE_INCLUDE" \
          "SDIR=$SDIR" "SOURCE=$SOURCE" "COMPILE_ARCH=$COMPILE_ARCH" \
+         "LIBS_DIR=$LIBS_DIR" \
          "SECLIB=$SECLIB" \
          "SECLIBS_STATIC=$SECLIBS_STATIC" \
          "WINGRIDLIB=$WINGRIDLIB" "WINGRIDLIB_DEP=$WINGRIDLIB_DEP" \
